[profile.default]
src = 'src'
out = 'out'
script = 'scripts'
libs = ['lib']
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/'
]

solc = "0.8.19"

fs_permissions = [{access = "write", path = "./reports"}]

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}

# See more config options https://github.com/gakonst/foundry/tree/master/config
